name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Selenium/requirements.txt

    - name: Run Selenium tests
      run: |
        pytest Selenium/tests/ --html=Selenium/reports/report.html --self-contained-html --maxfail=5 -v

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-report
        path: Selenium/reports/report.html
