name: Selenium Tests

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Selenium/requirements.txt  # Install project dependencies

    - name: Run Selenium tests
      run: |
        pytest Selenium/tests/ --html=Selenium/reports/report.html --self-contained-html  # Run tests and generate an HTML report

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-report
        path: Selenium/reports/report.html  # Upload the HTML report as an artifact
